// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteDesenvolvedor.Data;

namespace TesteDesenvolvedor.Migrations
{
    [DbContext(typeof(TesteDesenvolvedorContext))]
    [Migration("20220818232503_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteDesenvolvedor.Models.Cervejas", b =>
                {
                    b.Property<int>("IdCervejas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("IdCervejas");

                    b.ToTable("Cervejas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Models.ItensVenda", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CashbackItem")
                        .HasColumnType("float");

                    b.Property<int>("CervejasId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeItem")
                        .HasColumnType("int");

                    b.Property<double>("TotalItem")
                        .HasColumnType("float");

                    b.Property<int?>("VendasIdVendas")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.HasIndex("CervejasId");

                    b.HasIndex("VendasIdVendas");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Models.Vendas", b =>
                {
                    b.Property<int>("IdVendas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CashbackTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalVenda")
                        .HasColumnType("float");

                    b.HasKey("IdVendas");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Models.ItensVenda", b =>
                {
                    b.HasOne("TesteDesenvolvedor.Models.Cervejas", "Cerveja")
                        .WithMany()
                        .HasForeignKey("CervejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteDesenvolvedor.Models.Vendas", null)
                        .WithMany("ItensVenda")
                        .HasForeignKey("VendasIdVendas");

                    b.Navigation("Cerveja");
                });

            modelBuilder.Entity("TesteDesenvolvedor.Models.Vendas", b =>
                {
                    b.Navigation("ItensVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
